# Generated by Django 6.1.1 on 2026-09-17 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('forecast', 'Forecast'), ('observation', 'Observation'), ('reanalysis', 'Reanalysis')], max_length=20)),
                ('homepage', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('wind_speed_kt', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_gust_kt', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_direction_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pressure_hpa', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('precipitation_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wave_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wave_period_s', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wave_direction_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='spots.spot')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='weather.weathersource')),
            ],
            options={
                'ordering': ['observed_at'],
                'constraints': [models.UniqueConstraint(fields=('spot', 'source', 'observed_at'), name='unique_observation_per_source')],
            },
        ),
        migrations.CreateModel(
            name='ForecastPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(db_index=True)),
                ('valid_at', models.DateTimeField(db_index=True)),
                ('lead_hours', models.PositiveSmallIntegerField()),
                ('wind_speed_kt', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_gust_kt', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_direction_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pressure_hpa', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('precipitation_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wave_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wave_period_s', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wave_direction_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='spots.spot')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='weather.weathersource')),
            ],
            options={
                'ordering': ['valid_at'],
                'constraints': [models.UniqueConstraint(fields=('spot', 'source', 'issued_at', 'valid_at'), name='unique_forecast_point')],
            },
        ),
        migrations.CreateModel(
            name='DailyWindSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_date', models.DateField(db_index=True)),
                ('rideable_hours', models.PositiveSmallIntegerField(default=0)),
                ('fill_in_hour', models.PositiveSmallIntegerField(blank=True, help_text='Local hour (0-23) when wind first held in the rideable window.', null=True)),
                ('mean_wind_kt', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_gust_kt', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dominant_direction_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='spots.spot')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summaries', to='weather.weathersource')),
            ],
            options={
                'ordering': ['-local_date'],
                'constraints': [models.UniqueConstraint(fields=('spot', 'source', 'local_date'), name='unique_daily_summary')],
            },
        ),
    ]
