# Generated by Django 6.1.1 on 2026-09-17 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_preferred', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['distance_km'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.SlugField(help_text='meteostat, ndbc, grid, ...')),
                ('external_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('airport', 'Airport / METAR'), ('buoy', 'Buoy'), ('land', 'Land station'), ('grid', 'Model grid point')], max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('elevation_m', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=8)),
                ('icao', models.CharField(blank=True, max_length=8)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='observation',
            name='unique_observation_per_source',
        ),
        migrations.AddField(
            model_name='observation',
            name='extras',
            field=models.JSONField(blank=True, default=dict, help_text='Vendor fields that are not in the canonical kite columns.'),
        ),
        migrations.AddField(
            model_name='spotstation',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_links', to='spots.spot'),
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.UniqueConstraint(fields=('network', 'external_id'), name='unique_station'),
        ),
        migrations.AddField(
            model_name='spotstation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_links', to='weather.station'),
        ),
        migrations.AddField(
            model_name='observation',
            name='station',
            field=models.ForeignKey(blank=True, help_text='Sensor that produced this hour. Grid ingest uses a virtual station at the spot.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='weather.station'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(fields=('spot', 'station', 'source', 'observed_at'), name='unique_observation_per_station_source'),
        ),
        migrations.AddConstraint(
            model_name='spotstation',
            constraint=models.UniqueConstraint(fields=('spot', 'station'), name='unique_spot_station'),
        ),
    ]
