# Generated by Django 6.1.1 on 2026-09-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_backfill_grid_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastpoint',
            name='sea_level_m',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Sea surface height including tide, metres above global mean sea level.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='sea_level_m',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Sea surface height including tide, metres above global mean sea level.', max_digits=7, null=True),
        ),
    ]
