# Generated by Django 6.1.1 on 2026-09-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timezone', models.CharField(help_text='IANA timezone, e.g. America/New_York. Used to compute local fill-in hour.', max_length=64)),
                ('min_rideable_kt', models.PositiveSmallIntegerField(default=12)),
                ('max_rideable_kt', models.PositiveSmallIntegerField(default=30)),
                ('window_start_deg', models.PositiveSmallIntegerField(default=180, help_text='Clockwise start of the rideable wind sector, 0-359.')),
                ('window_end_deg', models.PositiveSmallIntegerField(default=270, help_text='Clockwise end of the rideable wind sector, 0-359.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
