# Generated by Django 6.1.1 on 2026-09-17 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='created_from_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spot',
            name='window_end_deg',
            field=models.PositiveSmallIntegerField(default=359, help_text='Clockwise end of the rideable wind sector, 0-359.'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='window_start_deg',
            field=models.PositiveSmallIntegerField(default=0, help_text='Clockwise start of the rideable wind sector, 0-359. 0-359 means all directions.'),
        ),
        migrations.CreateModel(
            name='SpotWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('tracked_at', models.DateTimeField(auto_now_add=True)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
                ('spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch', to='spots.spot')),
            ],
            options={
                'ordering': ['-is_favorite', 'spot__name'],
            },
        ),
    ]
