# Generated by Django 6.1.1 on 2026-09-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_spot_created_from_search_alter_spot_window_end_deg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='tide_preference',
            field=models.CharField(choices=[('any', 'Any tide'), ('incoming', 'Incoming / flooding'), ('outgoing', 'Outgoing / ebbing'), ('high', 'High'), ('low', 'Low')], default='any', help_text='Ocean spots often care about tide phase as much as wind.', max_length=16),
        ),
        migrations.AddField(
            model_name='spotwatch',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='Stop polling without deleting the archive.'),
        ),
    ]
