# Generated by Django 6.1.1 on 2026-09-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_spot_tide_preference_spotwatch_is_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='region_east',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='region_north',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='region_south',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='region_west',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
