# Generated by Django 6.1.1 on 2026-09-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_spot_region_east_spot_region_north_spot_region_south_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='region_polygon',
            field=models.JSONField(blank=True, help_text='List of {lat, lng} vertices. Weather is still scored at the centroid.', null=True),
        ),
    ]
